FROM python:3

#Layers for the django app
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install pip --upgrade
RUN pip install --upgrade -r requirements.txt

COPY . /code/

RUN python manage.py collectstatic --noinput

RUN groupadd -g 1000 uwsgi
RUN useradd -g uwsgi -ms /bin/bash uwsgi

