version: '3.7'

x-common-variables: &common-variables
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      <<: *common-variables
    command: /bin/sh -c "python manage.py migrate && uwsgi --ini uwsgi.ini --uid uwsgi --gid uwsgi --thunder-lock"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      VIRTUAL_HOST: ${HOST}
    command: /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/template.nginx > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    build:
      context: .
      dockerfile: Dockerfile.db

    environment:
      <<: *common-variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
